version: '3.8'

services:
  # ÉMULATEUR FIREBASE 
  database:
    image: andreysenov/firebase-tools:13.30.0 
    container_name: supcontent-db
    ports:
      - "4000:4000"
      - "8081:8081"
      - "9099:9099"
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: firebase emulators:start --project sup-content-tristan
    networks:
      - sup-network

  # BACKEND 
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    image: supcontent-backend:1.0
    container_name: supcontent-api
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - FIRESTORE_EMULATOR_HOST=database:8081
      - FIREBASE_AUTH_EMULATOR_HOST=database:9099
    depends_on:
      - database
    networks:
      - sup-network

  # FRONTEND 
  web:
    build:
      context: ./Frontend/bureau/front-ordi
      dockerfile: Dockerfile 
    image: supcontent-web:1.0
    container_name: supcontent-front
    ports:
      - "3001:5173"
    volumes:
      - ./Frontend/bureau/front-ordi:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - sup-network

networks:
  sup-network:
    driver: bridge