services:
  # ÉMULATEUR FIREBASE (Base de données locale)
  database:
    image: andreysenov/firebase-tools:latest
    container_name: supcontent-db
    ports:
      - "4000:4000" # UI de l'émulateur
      - "8081:8081" # Port Firestore
      - "9099:9099" # Port Auth
    volumes:
      - .:/home/node/app
      - firebase_cache:/home/node/.cache
    working_dir: /home/node/app
    command: >
      firebase emulators:start 
      --project sup-content-tristan 
      --import=./backend/data 
      --export-on-exit=./backend/data
    networks:
      - sup-network

  # BACKEND (Node 22) - API & IGDB Logic
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: supcontent-backend:1.0
    container_name: supcontent-api
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_vol:/app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - FIRESTORE_EMULATOR_HOST=database:8081
      - FIREBASE_AUTH_EMULATOR_HOST=database:9099
    depends_on:
      - database
    networks:
      - sup-network

  # FRONTEND (Node 22) - Vite / React
  web:
    build:
      context: ./Frontend/bureau/front-ordi
      dockerfile: Dockerfile
    image: supcontent-web:1.0
    container_name: supcontent-front
    ports:
      - "3001:5173"
    volumes:
      - ./Frontend/bureau/front-ordi:/app
      - web_vol:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - backend
    networks:
      - sup-network

networks:
  sup-network:
    driver: bridge

volumes:
  backend_vol:
  web_vol:
  db_vol:
  firebase_cache: