export const resources = {
  fr: {
    translation: {
      profileTitle: "Mon Profil",
      bioLabel: "Ma Biographie",
      langLabel: "Langue de l'interface",
      emailLabel: "Email de contact",
      btnUpdate: "METTRE À JOUR LE PROFIL",
      btnLogout: "SE DÉCONNECTER",
      homeTitle: "Tendances mondiales",
      homeSubtitle: "Tout le contenu SUPCONTENT à portée de clic.",
      genreGame: "Jeu",
      alertSuccess: "Profil mis à jour !",
      identifiedAs: "Identifié en tant que",
      placeholderBio: "Écrivez quelques mots sur vous...",
      signup_title: "Inscription",
      label_pseudo: "Pseudo",
      placeholder_pseudo: "Votre nom de joueur",
      label_email: "Email",
      placeholder_email: "votre@email.com",
      label_password: "Mot de passe",
      label_confirm_password: "Confirmer le mot de passe",
      button_signup: "S'INSCRIRE",
      loading: "Chargement...",
      already_registered: "Déjà inscrit ?",
      login_link: "Connexion",
      error_fields_empty: "Veuillez remplir tous les champs.",
      error_password_match: "Les mots de passe ne correspondent pas.",
    },
  },
  en: {
    translation: {
      profileTitle: "My Profile",
      bioLabel: "My Biography",
      langLabel: "Interface Language",
      emailLabel: "Contact Email",
      btnUpdate: "UPDATE PROFILE",
      btnLogout: "LOG OUT",
      homeTitle: "Global Trends",
      homeSubtitle: "All SUPCONTENT content at your fingertips.",
      genreGame: "Game",
      alertSuccess: "Profile updated!",
      identifiedAs: "Logged in as",
      placeholderBio: "Write a few words about yourself...",
      signup_title: "Sign Up",
      label_pseudo: "Username",
      placeholder_pseudo: "Your gamer name",
      label_email: "Email",
      placeholder_email: "your@email.com",
      label_password: "Password",
      label_confirm_password: "Confirm Password",
      button_signup: "SIGN UP",
      loading: "Loading...",
      already_registered: "Already registered?",
      login_link: "Login",
      error_fields_empty: "Please fill in all fields.",
      error_password_match: "Passwords do not match.",
    },
  },
};
