export const resources = {
  fr: {
    translation: {
      profileTitle: "Mon Profil",
      bioLabel: "Ma Biographie",
      websiteLabel: "Site Web",
      langLabel: "Langue de l'interface",
      emailLabel: "Email de contact",
      btnUpdate: "METTRE À JOUR LE PROFIL",
      btnLogout: "SE DÉCONNECTER",
      homeTitle: "Tendances mondiales",
      homeSubtitle: "Tout le contenu SUPCONTENT à portée de clic.",
      genreGame: "Jeu",
      alertSuccess: "Profil mis à jour !",
      identifiedAs: "Identifié en tant que",
      placeholderBio: "Écrivez quelques mots sur vous...",
      placeholderWebsite: "https://votre-site.com",
      signup_title: "Inscription",
      label_pseudo: "Pseudo",
      placeholder_pseudo: "Votre nom de joueur",
      label_email: "Email",
      placeholder_email: "votre@email.com",
      label_password: "Mot de passe",
      label_confirm_password: "Confirmer le mot de passe",
      button_signup: "S'INSCRIRE",
      loading: "Chargement...",
      already_registered: "Déjà inscrit ?",
      login_link: "Connexion",
      error_fields_empty: "Veuillez remplir tous les champs.",
      error_password_match: "Les mots de passe ne correspondent pas.",
      label_avatar: "Photo de profil (Fichier image)",
      label_birthdate: "Date de naissance",
      label_lang: "Langue de l'interface",
      edit_profile_title: "Modifier les informations",
      btn_edit_open: "Éditer le profil",
      btn_edit_close: "Fermer l'édition",
      section_collection: "Ma Collection",
      section_lists: "Mes Listes",
      btn_new_list: "Nouvelle liste",
      btn_cancel: "Annuler",
      filter_all: "Tous",
      filter_to_play: "À faire",
      filter_playing: "En cours",
      filter_finished: "Fini",
      filter_dropped: "Abandonné",
      library_empty:
        "Ta bibliothèque est vide. Ajoute des jeux pour les voir ici !",
      library_empty_filter: 'Aucun jeu dans la catégorie "{{filter}}"',
      no_bio: "Aucune bio renseignée.",
      stat_followers: "Abonnés",
      stat_following: "Abonnements",
      stat_games: "Jeux Favoris",
      lang_french: "Français",
      lang_english: "Anglais",
      lists_empty: "Cette liste est vide.",

      accueil_hero_title: "Découvrez les meilleurs jeux",
      accueil_hero_subtitle:
        "Tout le contenu sur TGMF à portée de clic. Explorez, filtrez et trouvez votre prochain jeu préféré.",
      accueil_tab_games: "Jeux",
      accueil_tab_members: "Membres",
      accueil_tab_admin: "Administration",
      accueil_results_for: 'Résultats pour "{{term}}"',
      accueil_trending: "Tendances mondiales",
      accueil_community_members: "Membres de la communauté",
      accueil_loading: "Chargement en cours...",
      accueil_connection_error_title: "Erreur de connexion",
      accueil_connection_error_text:
        "Impossible de contacter le service de recherche. Vérifiez votre connexion.",
      accueil_no_results_title: "Aucun résultat",
      accueil_no_results_text:
        "Essayez de modifier vos filtres ou votre recherche",
      accueil_passionate_player: "Joueur passionné",
      accueil_see_full_catalogue: "Voir tout le catalogue",
      accueil_upcoming_games: "Jeux à venir",
      accueil_loading_upcoming: "Chargement des jeux à venir...",
      accueil_no_upcoming_title: "Aucun jeu à venir",
      accueil_no_upcoming_text:
        "Restez à l'écoute, de nouveaux titres arrivent bientôt !",
      accueil_see_more: "Voir plus",
      accueil_tba: "À venir",
      btn_back: "Retour",
      default_username: "Joueur",
      avatar_alt: "Photo de profil",
      save_error: "Erreur lors de l'enregistrement",
      saving: "Enregistrement...",
      public_profile_title: "Profil de {{name}}",
      profile_tab_title: "Profil",
      error_login_required: "Vous devez être connecté pour voir ce profil.",
      error_profile_load: "Impossible de charger ce profil.",
      error_conversation_open: "Impossible d'ouvrir la conversation.",
      loading_profile: "Chargement du profil...",
      profile_not_found: "Profil introuvable",
      certified_profile: "Profil certifié",
      badge_mutual: "Abonnement mutuel",
      badge_follows_you: "Vous suit",
      badge_subscribed: "Abonné",
      btn_unfollow: "Se désabonner",
      btn_follow: "S'abonner",
      btn_send_message: "Envoyer un message",
      private_account_title: "Compte privé",
      private_account_desc:
        "Abonnez-vous mutuellement pour voir le contenu de ce profil.",
      public_collection_title: "Collection publique",
      public_collection_empty: "Aucun jeu dans la collection publique.",
      public_lists_title: "Listes publiques",
      list_empty: "Cette liste est vide.",

      form_create_list_title: "Créer une nouvelle liste",
      form_edit_list_title: "Modifier la liste",
      form_list_name_placeholder: "Nom de la liste",
      form_list_desc_placeholder: "Description (optionnel)",
      form_list_private_label: "Liste privée",
      btn_update: "Mettre à jour",
      btn_create_list: "Créer la liste",
      confirm_delete_list: "Voulez-vous vraiment supprimer cette liste ?",
      toast_list_deleted: "Liste supprimée.",
      toast_list_delete_error: "Erreur lors de la suppression de la liste.",
      badge_private: "Privée",
      badge_public: "Publique",
      list_game_count: "{{count}} jeu",
      list_game_count_plural: "{{count}} jeux",
      list_empty_add_hint: "Cette liste ne contient aucun jeu pour l'instant.",
      list_add_game_placeholder: "Rechercher un jeu à ajouter...",
      badge_added: "Ajouté",
      confirm_title: "Confirmation",
      btn_confirm: "Confirmer",

      my_account_private: "Compte privé",
      age_display: "{{age}} ans",

      notifications_title: "Notifications",
      notifications_new_count: "{{count}} nouvelle",
      notifications_new_count_plural: "{{count}} nouvelles",
      notifications_mark_all_read: "Tout marquer comme lu",
      notifications_empty: "Aucune notification pour le moment.",
      notif_someone: "Quelqu'un",
      notif_follow: "a commencé à vous suivre",
      notif_like: "a aimé votre contenu",
      notif_comment: "a commenté",
      notif_review: "a publié une critique",
      notif_message: "vous a envoyé un message",
      notif_thread_reply: "a répondu à votre message sur le forum",
      time_just_now: "À l'instant",
      time_minutes: "Il y a {{count}} minute",
      time_minutes_plural: "Il y a {{count}} minutes",
      time_hours: "Il y a {{count}} heure",
      time_hours_plural: "Il y a {{count}} heures",
      time_days: "Il y a {{count}} jour",
      time_days_plural: "Il y a {{count}} jours",
    },
  },
  en: {
    translation: {
      lists_empty: "This list is empty.",
      lang_french: "French",
      lang_english: "English",
      profileTitle: "My Profile",
      bioLabel: "My Biography",
      websiteLabel: "Website",
      langLabel: "Interface Language",
      emailLabel: "Contact Email",
      btnUpdate: "UPDATE PROFILE",
      btnLogout: "LOG OUT",
      homeTitle: "Global Trends",
      homeSubtitle: "All SUPCONTENT content at your fingertips.",
      genreGame: "Game",
      alertSuccess: "Profile updated!",
      identifiedAs: "Logged in as",
      placeholderBio: "Write a few words about yourself...",
      placeholderWebsite: "https://your-website.com",
      signup_title: "Sign Up",
      label_pseudo: "Username",
      placeholder_pseudo: "Your gamer name",
      label_email: "Email",
      placeholder_email: "your@email.com",
      label_password: "Password",
      label_confirm_password: "Confirm Password",
      button_signup: "SIGN UP",
      loading: "Loading...",
      already_registered: "Already registered?",
      login_link: "Login",
      error_fields_empty: "Please fill in all fields.",
      error_password_match: "Passwords do not match.",
      label_avatar: "Profile picture (Image file)",
      label_birthdate: "Date of birth",
      label_lang: "Interface Language",
      edit_profile_title: "Edit information",
      btn_edit_open: "Edit profile",
      btn_edit_close: "Close editor",
      section_collection: "My Collection",
      section_lists: "My Lists",
      btn_new_list: "New list",
      btn_cancel: "Cancel",
      filter_all: "All",
      filter_to_play: "To play",
      filter_playing: "Playing",
      filter_finished: "Finished",
      filter_dropped: "Dropped",
      library_empty: "Your library is empty. Add games to see them here!",
      library_empty_filter: 'No games in the "{{filter}}" category',
      no_bio: "No bio provided.",
      stat_followers: "Followers",
      stat_following: "Following",
      stat_games: "Favorite Games",

      accueil_hero_title: "Discover the best games",
      accueil_hero_subtitle:
        "All TGMF content at your fingertips. Explore, filter, and find your next favorite game.",
      accueil_tab_games: "Games",
      accueil_tab_members: "Members",
      accueil_tab_admin: "Administration",
      accueil_results_for: 'Results for "{{term}}"',
      accueil_trending: "Global Trends",
      accueil_community_members: "Community Members",
      accueil_loading: "Loading...",
      accueil_connection_error_title: "Connection Error",
      accueil_connection_error_text:
        "Unable to reach the search service. Please check your connection.",
      accueil_no_results_title: "No Results",
      accueil_no_results_text: "Try adjusting your filters or your search",
      accueil_passionate_player: "Passionate gamer",
      accueil_see_full_catalogue: "See the full catalogue",
      accueil_upcoming_games: "Upcoming Games",
      accueil_loading_upcoming: "Loading upcoming games...",
      accueil_no_upcoming_title: "No Upcoming Games",
      accueil_no_upcoming_text: "Stay tuned, new titles are coming soon!",
      accueil_see_more: "See more",
      accueil_tba: "TBA",

      btn_back: "Back",
      default_username: "Player",
      avatar_alt: "Profile picture",
      save_error: "Error while saving",
      saving: "Saving...",

      public_profile_title: "{{name}}'s profile",
      profile_tab_title: "Profile",
      error_login_required: "You must be logged in to view this profile.",
      error_profile_load: "Unable to load this profile.",
      error_conversation_open: "Unable to open the conversation.",
      loading_profile: "Loading profile...",
      profile_not_found: "Profile not found",
      certified_profile: "Certified profile",
      badge_mutual: "Mutual follow",
      badge_follows_you: "Follows you",
      badge_subscribed: "Following",
      btn_unfollow: "Unfollow",
      btn_follow: "Follow",
      btn_send_message: "Send message",
      private_account_title: "Private account",
      private_account_desc: "Follow each other to see this profile's content.",
      public_collection_title: "Public collection",
      public_collection_empty: "No games in the public collection.",
      public_lists_title: "Public lists",
      list_empty: "This list is empty.",

      form_create_list_title: "Create a new list",
      form_edit_list_title: "Edit list",
      form_list_name_placeholder: "List name",
      form_list_desc_placeholder: "Description (optional)",
      form_list_private_label: "Private list",
      btn_update: "Update",
      btn_create_list: "Create list",
      confirm_delete_list: "Are you sure you want to delete this list?",
      toast_list_deleted: "List deleted.",
      toast_list_delete_error: "Error while deleting the list.",
      badge_private: "Private",
      badge_public: "Public",
      list_game_count: "{{count}} game",
      list_game_count_plural: "{{count}} games",
      list_empty_add_hint: "This list doesn't contain any games yet.",
      list_add_game_placeholder: "Search for a game to add...",
      badge_added: "Added",
      confirm_title: "Confirmation",
      btn_confirm: "Confirm",

      my_account_private: "Private account",
      age_display: "{{age}} years old",

      notifications_title: "Notifications",
      notifications_new_count: "{{count}} new",
      notifications_new_count_plural: "{{count}} new",
      notifications_mark_all_read: "Mark all as read",
      notifications_empty: "No notifications yet.",
      notif_someone: "Someone",
      notif_follow: "started following you",
      notif_like: "liked your content",
      notif_comment: "commented",
      notif_review: "posted a review",
      notif_message: "sent you a message",
      notif_thread_reply: "replied to your forum post",
      time_just_now: "Just now",
      time_minutes: "{{count}} minute ago",
      time_minutes_plural: "{{count}} minutes ago",
      time_hours: "{{count}} hour ago",
      time_hours_plural: "{{count}} hours ago",
      time_days: "{{count}} day ago",
      time_days_plural: "{{count}} days ago",
    },
  },
};
