export const resources = {
  fr: {
    translation: {
      profileTitle: "Mon Profil",
      bioLabel: "Ma Biographie",
      websiteLabel: "Site Web",
      langLabel: "Langue de l'interface",
      emailLabel: "Email de contact",
      btnUpdate: "METTRE À JOUR LE PROFIL",
      btnLogout: "SE DÉCONNECTER",
      homeTitle: "Tendances mondiales",
      homeSubtitle: "Tout le contenu SUPCONTENT à portée de clic.",
      genreGame: "Jeu",
      alertSuccess: "Profil mis à jour !",
      identifiedAs: "Identifié en tant que",
      placeholderBio: "Écrivez quelques mots sur vous...",
      placeholderWebsite: "https://votre-site.com",
      signup_title: "Inscription",
      label_pseudo: "Pseudo",
      placeholder_pseudo: "Votre nom de joueur",
      label_email: "Email",
      placeholder_email: "votre@email.com",
      label_password: "Mot de passe",
      label_confirm_password: "Confirmer le mot de passe",
      button_signup: "S'INSCRIRE",
      loading: "Chargement...",
      already_registered: "Déjà inscrit ?",
      login_link: "Connexion",
      error_fields_empty: "Veuillez remplir tous les champs.",
      error_password_match: "Les mots de passe ne correspondent pas.",
      label_avatar: "Photo de profil (Fichier image)",
      label_birthdate: "Date de naissance",
      label_lang: "Langue de l'interface",
      edit_profile_title: "Modifier les informations",
      btn_edit_open: "Éditer le profil",
      btn_edit_close: "Fermer l'édition",
      section_collection: "Ma Collection",
      section_lists: "Mes Listes",
      btn_new_list: "Nouvelle liste",
      btn_cancel: "Annuler",
      filter_all: "Tous",
      filter_to_play: "À faire",
      filter_playing: "En cours",
      filter_finished: "Fini",
      filter_dropped: "Abandonné",
      library_empty:
        "Ta bibliothèque est vide. Ajoute des jeux pour les voir ici !",
      library_empty_filter: 'Aucun jeu dans la catégorie "{{filter}}"',
      no_bio: "Aucune bio renseignée.",
      stat_followers: "Abonnés",
      stat_following: "Abonnements",
      stat_games: "Jeux Favoris",
      lang_french: "Français",
      lang_english: "Anglais",
      lists_empty: "Cette liste est vide.",

      // --- Accueil.jsx ---
      accueil_hero_title: "Découvrez les meilleurs jeux",
      accueil_hero_subtitle:
        "Tout le contenu sur TGMF à portée de clic. Explorez, filtrez et trouvez votre prochain jeu préféré.",
      accueil_tab_games: "Jeux",
      accueil_tab_members: "Membres",
      accueil_tab_admin: "Administration",
      accueil_results_for: 'Résultats pour "{{term}}"',
      accueil_trending: "Tendances mondiales",
      accueil_community_members: "Membres de la communauté",
      accueil_loading: "Chargement en cours...",
      accueil_connection_error_title: "Erreur de connexion",
      accueil_connection_error_text:
        "Impossible de contacter le service de recherche. Vérifiez votre connexion.",
      accueil_no_results_title: "Aucun résultat",
      accueil_no_results_text:
        "Essayez de modifier vos filtres ou votre recherche",
      accueil_passionate_player: "Joueur passionné",
      accueil_see_full_catalogue: "Voir tout le catalogue",
      accueil_upcoming_games: "Jeux à venir",
      accueil_loading_upcoming: "Chargement des jeux à venir...",
      accueil_no_upcoming_title: "Aucun jeu à venir",
      accueil_no_upcoming_text:
        "Restez à l'écoute, de nouveaux titres arrivent bientôt !",
      accueil_see_more: "Voir plus",
      accueil_tba: "À venir",
    },
  },
  en: {
    translation: {
      lists_empty: "This list is empty.",
      lang_french: "French",
      lang_english: "English",
      profileTitle: "My Profile",
      bioLabel: "My Biography",
      websiteLabel: "Website",
      langLabel: "Interface Language",
      emailLabel: "Contact Email",
      btnUpdate: "UPDATE PROFILE",
      btnLogout: "LOG OUT",
      homeTitle: "Global Trends",
      homeSubtitle: "All SUPCONTENT content at your fingertips.",
      genreGame: "Game",
      alertSuccess: "Profile updated!",
      identifiedAs: "Logged in as",
      placeholderBio: "Write a few words about yourself...",
      placeholderWebsite: "https://your-website.com",
      signup_title: "Sign Up",
      label_pseudo: "Username",
      placeholder_pseudo: "Your gamer name",
      label_email: "Email",
      placeholder_email: "your@email.com",
      label_password: "Password",
      label_confirm_password: "Confirm Password",
      button_signup: "SIGN UP",
      loading: "Loading...",
      already_registered: "Already registered?",
      login_link: "Login",
      error_fields_empty: "Please fill in all fields.",
      error_password_match: "Passwords do not match.",
      label_avatar: "Profile picture (Image file)",
      label_birthdate: "Date of birth",
      label_lang: "Interface Language",
      edit_profile_title: "Edit information",
      btn_edit_open: "Edit profile",
      btn_edit_close: "Close editor",
      section_collection: "My Collection",
      section_lists: "My Lists",
      btn_new_list: "New list",
      btn_cancel: "Cancel",
      filter_all: "All",
      filter_to_play: "To play",
      filter_playing: "Playing",
      filter_finished: "Finished",
      filter_dropped: "Dropped",
      library_empty: "Your library is empty. Add games to see them here!",
      library_empty_filter: 'No games in the "{{filter}}" category',
      no_bio: "No bio provided.",
      stat_followers: "Followers",
      stat_following: "Following",
      stat_games: "Favorite Games",

      // --- Accueil.jsx ---
      accueil_hero_title: "Discover the best games",
      accueil_hero_subtitle:
        "All TGMF content at your fingertips. Explore, filter, and find your next favorite game.",
      accueil_tab_games: "Games",
      accueil_tab_members: "Members",
      accueil_tab_admin: "Administration",
      accueil_results_for: 'Results for "{{term}}"',
      accueil_trending: "Global Trends",
      accueil_community_members: "Community Members",
      accueil_loading: "Loading...",
      accueil_connection_error_title: "Connection Error",
      accueil_connection_error_text:
        "Unable to reach the search service. Please check your connection.",
      accueil_no_results_title: "No Results",
      accueil_no_results_text: "Try adjusting your filters or your search",
      accueil_passionate_player: "Passionate gamer",
      accueil_see_full_catalogue: "See the full catalogue",
      accueil_upcoming_games: "Upcoming Games",
      accueil_loading_upcoming: "Loading upcoming games...",
      accueil_no_upcoming_title: "No Upcoming Games",
      accueil_no_upcoming_text: "Stay tuned, new titles are coming soon!",
      accueil_see_more: "See more",
      accueil_tba: "TBA",
    },
  },
};
